### ISSUE TITLE
Captures broken

### ISSUE THREAD

**Issue by dbqpdb** [dbqpdb/RLM#5]
`rlm` currently doesn't permit any captures. This is true in both `comment-branch` and `master`, so the problem is prior to our last commit.

**Comment by mikebind** [comment]
In the RLM vs RLM PGN I posted, there are a number of captures, including pawn captures, but as I play now, I can't do a pawn capture which is entirely legal...

**Comment by mikebind** [comment]
The most recent version of the comment-branch has some new functionality to explore this bug.  After the user fails to enter a legal move once, they get the same message they used to get "Tut,tut...", but after they fail again, they get a suggested random legal move (in the spirit of the RLM).  If they fail again, then the RLM prints out ALL legal moves from it's legal move list.  

I have verified that the full list of legal moves generated is missing legal captures in the few positions I tried. I'm going to have to stop investigating for tonight, but may be able to work some more on it tomorrow. Super odd that this was clearly working before and is failing now.

**Comment by mikebind** [comment]
Should be fixed now on both the comment-branch and the master branch. The problem came from inconsistent use of separator, which was $separator in some places and a hard-coded "turkeyburp" in some places.  So, changing $separator to "turkeyblurp" led to separation failures, which caused errors in move processing.
